var businessReport = {
    report: {
        name: 'reportRoot',
        type: 'report',
        paperSize: 'A4',
        paperWidth: '210mm',
        paperHeight: '297mm',
        marginLeft: '15mm',
        marginRight: '15mm',
        marginTop: '15mm',
        marginBottom: '15mm',
    },
    page: {
        name: 'reportPage',
        type: 'report',
        pageHeader: { name: 'pageHeader' },
        reportHeader: {
            name: 'reportHeader',
            items: [
                {
                    type: 'text',
                    left: 0,
                    top: 26,
                    text: '출장계획보고서',
                    styles: { fontSize: '20px', fontWeight: 'bold' },
                },
                {
                    type: 'table',
                    width: 229.2913385826771,
                    name: '',
                    right: '0px',
                    rowCount: 2,
                    fixed: false,
                    minRowHeight: '24px',
                    cellStyles: {},
                    rows: [{}, { height: '50px' }],
                    cells: [],
                    colCount: 4,
                    columns: [
                        { width: '25%' },
                        { width: '25%' },
                        { width: '25%' },
                        { width: '25%' },
                    ],
                    items: [
                        {
                            type: 'text',
                            col: 0,
                            row: 0,
                            text: '담당',
                            styles: { fontSize: '12px' },
                        },
                        {
                            type: 'sign',
                            width: '100%',
                            height: '100%',
                            col: 0,
                            row: 1,
                        },
                    ],
                },
            ],
        },
        reportFooter: { name: 'reportFooter' },
        pageFooter: { name: 'pageFooter' },
        body: {
            itemGap: 0,
            items: [
                { type: 'space', size: '30px' },
                {
                    type: 'simpleband',
                    data: 'business',
                    width: '100%',
                    detail: { type: 'details', width: '100%', name: '' },
                    groups: [],
                    header: { type: 'stack', width: '100%', name: null },
                    footer: { type: 'stack', width: '100%', name: null },
                    dataRow: {
                        type: 'stack',
                        data: 'business',
                        width: '100%',
                        name: null,
                        items: [
                            {
                                type: 'table',
                                width: '100%',
                                name: '',
                                rowCount: 3,
                                fixed: true,
                                minRowHeight: '27px',
                                cellStyles: {},
                                rows: [{}, {}, {}],
                                cells: [
                                    {
                                        r: 0,
                                        c: 0,
                                        styles: {
                                            backgroundColor: '#f3f3f3',
                                            borderLeft: 'none',
                                            borderTop: '2px solid #111',
                                        },
                                    },
                                    {
                                        r: 0,
                                        c: 1,
                                        styles: {
                                            borderRight: 'none',
                                            borderTop: '2px solid #111',
                                        },
                                    },
                                    {
                                        r: 0,
                                        c: 2,
                                        styles: {
                                            backgroundColor: '#f3f3f3',
                                            borderRight: 'none',
                                            borderTop: '2px solid #111',
                                        },
                                    },
                                    {
                                        r: 0,
                                        c: 3,
                                        styles: {
                                            borderRight: 'none',
                                            borderTop: '2px solid #111',
                                        },
                                    },
                                    {
                                        r: 0,
                                        c: 4,
                                        styles: {
                                            backgroundColor: '#f3f3f3',
                                            borderRight: 'none',
                                            borderTop: '2px solid #111',
                                        },
                                    },
                                    {
                                        r: 0,
                                        c: 5,
                                        styles: {
                                            borderRight: 'none',
                                            borderTop: '2px solid #111',
                                        },
                                    },
                                    {
                                        r: 1,
                                        c: 0,
                                        styles: {
                                            backgroundColor: '#f3f3f3',
                                            borderLeft: 'none',
                                            borderTop: 'none',
                                        },
                                    },
                                    { r: 1, c: 1, colspan: 2 },
                                    {
                                        r: 1,
                                        c: 3,
                                        styles: { backgroundColor: '#f3f3f3' },
                                    },
                                    {
                                        r: 1,
                                        c: 4,
                                        colspan: 2,
                                        styles: { borderRight: 'none' },
                                    },
                                    {
                                        r: 2,
                                        c: 0,
                                        styles: {
                                            backgroundColor: '#f3f3f3',
                                            borderLeft: 'none',
                                            borderBottom: 'none',
                                        },
                                    },
                                    {
                                        r: 2,
                                        c: 1,
                                        colspan: 5,
                                        styles: {
                                            borderRight: 'none',
                                            borderBottom: 'none',
                                        },
                                    },
                                ],
                                colCount: 6,
                                columns: [
                                    { width: '110px' },
                                    { width: '128px' },
                                    { width: '110px' },
                                    { width: '110px' },
                                    { width: '110px' },
                                    { width: '110px' },
                                ],
                                items: [
                                    {
                                        type: 'text',
                                        col: 0,
                                        row: 0,
                                        text: '소속',
                                        styles: { fontSize: '12px' },
                                    },
                                    {
                                        type: 'text',
                                        col: 2,
                                        row: 0,
                                        text: '직위',
                                        styles: { fontSize: '12px' },
                                    },
                                    {
                                        type: 'text',
                                        col: 4,
                                        row: 0,
                                        text: '성명',
                                        styles: { fontSize: '12px' },
                                    },
                                    {
                                        type: 'text',
                                        col: 3,
                                        row: 1,
                                        text: '출장지',
                                        styles: { fontSize: '12px' },
                                    },
                                    {
                                        type: 'text',
                                        col: 0,
                                        row: 1,
                                        text: '작성일',
                                        styles: { fontSize: '12px' },
                                    },
                                    {
                                        type: 'text',
                                        col: 0,
                                        row: 2,
                                        text: '출장기간',
                                        styles: { fontSize: '12px' },
                                    },
                                    {
                                        type: 'text',
                                        value: 'department',
                                        width: '100%',
                                        col: 1,
                                        row: 0,
                                        text: 'Text',
                                        autoShrink: true,
                                        styles: { fontSize: '12px' },
                                    },
                                    {
                                        type: 'text',
                                        value: 'position',
                                        width: '100%',
                                        col: 3,
                                        row: 0,
                                        text: 'Text',
                                        autoShrink: true,
                                        styles: { fontSize: '12px' },
                                    },
                                    {
                                        type: 'text',
                                        value: 'name',
                                        width: '100%',
                                        col: 5,
                                        row: 0,
                                        text: 'Text',
                                        autoShrink: true,
                                        styles: { fontSize: '12px' },
                                    },
                                    {
                                        type: 'text',
                                        value: 'date',
                                        width: '100%',
                                        col: 1,
                                        row: 1,
                                        text: 'Text',
                                        autoShrink: true,
                                        styles: { fontSize: '12px' },
                                    },
                                    {
                                        type: 'text',
                                        value: 'destination',
                                        width: '100%',
                                        col: 4,
                                        row: 1,
                                        text: 'Text',
                                        autoShrink: true,
                                        styles: { fontSize: '12px' },
                                    },
                                    {
                                        type: 'text',
                                        value: 'period',
                                        width: '100%',
                                        col: 1,
                                        row: 2,
                                        text: 'Text',
                                        autoShrink: true,
                                        styles: { fontSize: '12px' },
                                    },
                                ],
                            },
                        ],
                    },
                },
                {
                    type: 'bandgroup',
                    width: '100%',
                    bandGap: 0,
                    direction: 'horizontal',
                    items: [
                        {
                            type: 'bandcell',
                            weight: 1,
                            size: 110.5,
                            styles: {
                                backgroundColor: '#f3f3f3',
                                borderRight: '1px solid #aaa',
                                borderBottom: 'none',
                                borderLeft: 'none',
                                borderTop: '1px solid #aaa',
                            },
                            items: [
                                {
                                    type: 'text',
                                    width: '100%',
                                    text: '출장목적',
                                    styles: {
                                        fontSize: '12px',
                                        borderLeft: 'none',
                                    },
                                },
                            ],
                        },
                        {
                            type: 'bandcell',
                            weight: 1,
                            items: [
                                {
                                    type: 'tableband',
                                    data: 'business-purpose',
                                    width: '100%',
                                    name: '',
                                    detail: {
                                        type: 'details',
                                        width: '100%',
                                        name: '',
                                    },
                                    colCount: 1,
                                    columns: [{ width: '20%' }],
                                    header: {
                                        width: '100%',
                                        name: '',
                                        visible: false,
                                        rowCount: 1,
                                        fixed: false,
                                        cellStyles: {},
                                        rows: [{}],
                                        cells: [],
                                    },
                                    footer: {
                                        width: '100%',
                                        name: '',
                                        visible: false,
                                        rowCount: 1,
                                        fixed: false,
                                        cellStyles: {},
                                        rows: [{}],
                                        cells: [],
                                    },
                                    dataRow: {
                                        width: '100%',
                                        name: '',
                                        onGetStyles:
                                            "debugger;\n\tif (row === 0) {\n\t  return {\n\t    borderTop: 'none'\n\t  }\n\t}",
                                        rowCount: 1,
                                        fixed: false,
                                        cellStyles: {
                                            borderLeft: 'none',
                                            borderTop: 'none',
                                            borderBottom: 'none',
                                        },
                                        rows: [{ height: '27px' }],
                                        cells: [
                                            {
                                                r: 0,
                                                c: 0,
                                                styles: {
                                                    borderRight: 'none',
                                                    borderTop: '1px solid #aaa',
                                                    borderBottom: 'none',
                                                },
                                            },
                                        ],
                                        items: [
                                            {
                                                type: 'text',
                                                value: 'purpose',
                                                width: '100%',
                                                name: '',
                                                col: 0,
                                                row: 0,
                                                styles: {
                                                    fontSize: '12px',
                                                    textAlign: 'left',
                                                    paddingLeft: '10px',
                                                },
                                            },
                                        ],
                                    },
                                    styles: {
                                        borderLeft: 'none',
                                        borderRight: 'none',
                                    },
                                },
                            ],
                        },
                    ],
                },
                {
                    type: 'tableband',
                    data: 'business-detail',
                    width: '100%',
                    name: '',
                    masterFields: 'id',
                    keyFields: 'id',
                    maxEndRowCount: 18,
                    detail: { type: 'details', width: '100%', name: '' },
                    colCount: 4,
                    columns: [
                        { width: '153px' },
                        { width: '20%' },
                        { width: '120px' },
                        { width: '120px' },
                    ],
                    header: {
                        width: '100%',
                        name: '',
                        rowCount: 1,
                        fixed: false,
                        cellStyles: {
                            borderLeft: 'none',
                            borderRight: 'none',
                            borderTop: 'none',
                            borderBottom: 'none',
                        },
                        rows: [{}],
                        cells: [{ r: 0, c: 0, colspan: 4 }],
                        items: [
                            {
                                type: 'table',
                                width: '100%',
                                name: '',
                                col: 0,
                                row: 0,
                                rowCount: 2,
                                fixed: false,
                                minRowHeight: '27px',
                                cellStyles: { borderTop: '1px solid #aaa' },
                                rows: [{}, {}],
                                cells: [
                                    {
                                        r: 0,
                                        c: 0,
                                        colspan: 4,
                                        styles: {
                                            backgroundColor: '#f3f3f3',
                                            borderLeft: 'none',
                                            borderRight: 'none',
                                            borderTop: '1px solid #aaa',
                                        },
                                    },
                                    {
                                        r: 0,
                                        c: 1,
                                        styles: {
                                            borderLeft:
                                                '1px dotted rgb(17, 17, 17)',
                                            borderTop: 'none',
                                        },
                                    },
                                    {
                                        r: 0,
                                        c: 2,
                                        styles: {
                                            borderLeft:
                                                '1px dotted rgb(17, 17, 17)',
                                            borderTop: 'none',
                                        },
                                    },
                                    {
                                        r: 0,
                                        c: 3,
                                        styles: {
                                            borderRight: 'none',
                                            borderTop: 'none',
                                        },
                                    },
                                    {
                                        r: 1,
                                        c: 0,
                                        styles: {
                                            backgroundColor: '#f3f3f3',
                                            borderLeft: 'none',
                                        },
                                    },
                                    {
                                        r: 1,
                                        c: 1,
                                        styles: { backgroundColor: '#f3f3f3' },
                                    },
                                    {
                                        r: 1,
                                        c: 2,
                                        styles: { backgroundColor: '#f3f3f3' },
                                    },
                                    {
                                        r: 1,
                                        c: 3,
                                        styles: {
                                            backgroundColor: '#f3f3f3',
                                            borderRight: 'none',
                                        },
                                    },
                                ],
                                colCount: 4,
                                columns: [
                                    { width: '153px' },
                                    { width: '37.7%' },
                                    { width: '120px' },
                                    { width: '120px' },
                                ],
                                items: [
                                    {
                                        type: 'text',
                                        col: 0,
                                        row: 0,
                                        text: '출장비 상세내역',
                                        styles: { fontSize: '12px' },
                                    },
                                    {
                                        type: 'text',
                                        width: '100%',
                                        col: 0,
                                        row: 1,
                                        text: '지출항목',
                                        styles: { fontSize: '12px' },
                                    },
                                    {
                                        type: 'text',
                                        width: '100%',
                                        col: 1,
                                        row: 1,
                                        text: '지출예정',
                                        styles: { fontSize: '12px' },
                                    },
                                    {
                                        type: 'text',
                                        width: '100%',
                                        col: 2,
                                        row: 1,
                                        text: '계획',
                                        styles: { fontSize: '12px' },
                                    },
                                    {
                                        type: 'text',
                                        width: '100%',
                                        col: 3,
                                        row: 1,
                                        text: '실지출금',
                                        styles: { fontSize: '12px' },
                                    },
                                ],
                            },
                        ],
                    },
                    footer: {
                        width: '100%',
                        name: '',
                        rowCount: 1,
                        fixed: false,
                        cellStyles: { borderBottom: '2px solid #111' },
                        rows: [{ height: '27px' }],
                        cells: [
                            {
                                r: 0,
                                c: 0,
                                colspan: 2,
                                styles: {
                                    cellAlign: 'left',
                                    borderLeft: 'none',
                                },
                            },
                            { r: 0, c: 3, styles: { borderRight: 'none' } },
                        ],
                        items: [
                            {
                                type: 'text',
                                col: 0,
                                row: 0,
                                text: '합계',
                                styles: {
                                    fontSize: '12px',
                                    textAlign: 'left',
                                    paddingLeft: '10px',
                                },
                            },
                            {
                                type: 'summary',
                                width: '100%',
                                col: 2,
                                row: 0,
                                prefix: '',
                                suffix: '원',
                                expression: 'sum(planned)',
                                styles: {
                                    textAlign: 'right',
                                    paddingRight: '10px',
                                },
                            },
                            {
                                type: 'summary',
                                width: '100%',
                                col: 3,
                                row: 0,
                                suffix: '원',
                                expression: 'sum(actual)',
                                styles: {
                                    textAlign: 'right',
                                    paddingRight: '16px',
                                },
                            },
                        ],
                    },
                    dataRow: {
                        width: '100%',
                        name: '',
                        rowCount: 1,
                        fixed: false,
                        cellStyles: {
                            borderLeft: '',
                            borderRight: '',
                            borderTop: 'none',
                            borderBottom: '',
                        },
                        rows: [{ height: '27px' }],
                        cells: [
                            {
                                r: 0,
                                c: 0,
                                colspan: 4,
                                styles: {
                                    borderLeft: 'none',
                                    borderRight: 'none',
                                },
                            },
                            { r: 0, c: 3, styles: { borderRight: 'none' } },
                        ],
                        items: [
                            {
                                type: 'table',
                                width: '100%',
                                name: '',
                                col: 0,
                                row: 0,
                                rowCount: 1,
                                fixed: false,
                                minRowHeight: '24px',
                                cellStyles: { borderLeft: '', borderRight: '' },
                                rows: [{ height: '27px' }],
                                cells: [
                                    {
                                        r: 0,
                                        c: 0,
                                        styles: {
                                            borderLeft: 'none',
                                            borderTop: 'none',
                                        },
                                    },
                                    {
                                        r: 0,
                                        c: 1,
                                        styles: { borderTop: 'none' },
                                    },
                                    {
                                        r: 0,
                                        c: 2,
                                        styles: { borderTop: 'none' },
                                    },
                                    {
                                        r: 0,
                                        c: 3,
                                        styles: {
                                            borderRight: 'none',
                                            borderTop: 'none',
                                        },
                                    },
                                ],
                                colCount: 4,
                                columns: [
                                    { width: '153px' },
                                    { width: '25%' },
                                    { width: '120px' },
                                    { width: '120px' },
                                ],
                                items: [
                                    {
                                        type: 'text',
                                        value: 'field',
                                        width: '100%',
                                        name: '',
                                        col: 0,
                                        row: 0,
                                        styles: { borderLeft: 'none' },
                                    },
                                    {
                                        type: 'text',
                                        value: 'estimated',
                                        width: '100%',
                                        name: '',
                                        col: 1,
                                        row: 0,
                                        autoShrink: true,
                                        styles: {
                                            textAlign: 'left',
                                            paddingLeft: '10px',
                                        },
                                    },
                                    {
                                        type: 'text',
                                        value: 'planned',
                                        width: '100%',
                                        name: '',
                                        col: 2,
                                        row: 0,
                                        suffix: '원',
                                        styles: {
                                            textAlign: 'right',
                                            paddingRight: '10px',
                                        },
                                    },
                                    {
                                        type: 'text',
                                        value: 'actual',
                                        width: '100%',
                                        name: '',
                                        col: 3,
                                        row: 0,
                                        suffix: '원',
                                        styles: {
                                            textAlign: 'right',
                                            paddingRight: '10px',
                                            borderRight: 'none',
                                        },
                                    },
                                ],
                            },
                        ],
                    },
                },
            ],
        },
    },
    data: {
        business: {
            type: 'band',
            fields: [
                {
                    fieldName: 'department',
                    label: '',
                    dataType: 'text',
                    source: '',
                    format: '',
                    sample: '',
                    description: '',
                    dateReader: null,
                },
                {
                    fieldName: 'position',
                    label: '',
                    dataType: 'text',
                    source: '',
                    format: '',
                    sample: '',
                    description: '',
                    dateReader: null,
                },
                {
                    fieldName: 'name',
                    label: '',
                    dataType: 'text',
                    source: '',
                    format: '',
                    sample: '',
                    description: '',
                    dateReader: null,
                },
                {
                    fieldName: 'date',
                    label: '',
                    dataType: 'text',
                    source: '',
                    format: '',
                    sample: '',
                    description: '',
                    dateReader: null,
                },
                {
                    fieldName: 'destination',
                    label: '',
                    dataType: 'text',
                    source: '',
                    format: '',
                    sample: '',
                    description: '',
                    dateReader: null,
                },
                {
                    fieldName: 'period',
                    dataType: 'text',
                    sample: '',
                    dateReader: null,
                },
                {
                    fieldName: 'id',
                    dataType: 'text',
                    sample: '',
                    dateReader: null,
                },
                {
                    fieldName: 'purpose',
                    dataType: 'text',
                    sample: '',
                    dateReader: null,
                },
            ],
            sample: [
                {
                    department: '엔터프라이즈 솔루션 본부',
                    position: '엔지니어',
                    name: '김민재',
                    date: '2025년 7월 16일',
                    destination: '에이펙스테크 본사 (대전광역시)',
                    period: '2025년 7월 17일 ~ 7월 18일',
                    id: '1',
                    purpose: '',
                },
            ],
        },
        'business-detail': {
            type: 'band',
            fields: [
                {
                    fieldName: 'field',
                    label: '',
                    dataType: 'text',
                    source: '',
                    format: '',
                    sample: '',
                    description: '',
                    dateReader: null,
                },
                {
                    fieldName: 'estimated',
                    label: '',
                    dataType: 'text',
                    source: '',
                    format: '',
                    sample: '',
                    description: '',
                    dateReader: null,
                },
                {
                    fieldName: 'planned',
                    label: '',
                    dataType: 'number',
                    source: '',
                    format: '',
                    sample: '',
                    description: '',
                    dateReader: null,
                },
                {
                    fieldName: 'actual',
                    label: '',
                    dataType: 'number',
                    source: '',
                    format: '',
                    sample: '',
                    description: '',
                    dateReader: null,
                },
                {
                    fieldName: 'id',
                    dataType: 'text',
                    sample: '',
                    dateReader: null,
                },
            ],
            sample: [
                {
                    field: '교통비',
                    estimated: 'KTX 왕복 (서울 ↔ 대전)',
                    planned: '56000',
                    actual: '56000',
                    id: '1',
                },
                {
                    field: '숙박비',
                    estimated: '대전역 인근 호텔 1박 (호텔다움)',
                    planned: '85000',
                    actual: '82000',
                    id: '1',
                },
                {
                    field: '식대',
                    estimated: '중식/석식 (2회)',
                    planned: '32000',
                    actual: '31200',
                    id: '1',
                },
                {
                    field: '일비',
                    estimated: '출장 일당 (사내 규정 기준)',
                    planned: '20000',
                    actual: '20000',
                    id: '1',
                },
                {
                    field: '기타',
                    estimated: '에이펙스테크 주차비 및 커피 회의비 ',
                    planned: '12000',
                    actual: '11500',
                    id: '1',
                },
            ],
        },
        'business-purpose': {
            type: 'band',
            fields: [
                {
                    fieldName: 'purpose',
                    label: '',
                    dataType: 'text',
                    source: '',
                    format: '',
                    sample: '',
                    description: '',
                    dateReader: null,
                },
            ],
            sample: [
                {
                    purpose: '에이펙스테크 전산실 서버 및 네트워크 진단 수행',
                },
                {
                    purpose: '피크 타임 발생 중인 트래픽 과부하 이슈 해결',
                },
                {
                    purpose:
                        '영업팀과 신규 CRM 기능 요구사항 및 도입 일정 협의',
                },
                {
                    purpose:
                        '현장 테스트 환경 구축 및 기능 시연을 통한 사용자 피드백 수집',
                },
            ],
        },
    },
};
