var employmentContract = {
    report: {
        name: 'reportRoot',
        type: 'report',
        paperSize: 'A4',
        paperWidth: '210mm',
        paperHeight: '297mm',
        marginLeft: '17mm',
        marginRight: '17mm',
        marginTop: '15mm',
        marginBottom: '15mm',
    },
    page: {
        name: 'reportPage',
        type: 'report',
        pageHeader: {
            name: 'pageHeader',
            items: [
                {
                    type: 'text',
                    height: 34,
                    text: '단시간근로자 표준근로계약서',
                    styles: {
                        fontSize: '22px',
                        border: '1px solid black',
                        paddingLeft: '30px',
                        paddingRight: '30px',
                        paddingTop: '5px',
                        paddingBottom: '5px',
                        fontWeight: '600',
                    },
                },
            ],
        },
        reportHeader: { name: 'reportHeader' },
        reportFooter: { name: 'reportFooter' },
        pageFooter: { name: 'pageFooter' },
        body: {
            itemGap: '10px',
            items: [
                { type: 'space', size: 15, styles: { fontSize: '15px' } },
                {
                    type: 'simpleband',
                    data: 'employmentContract',
                    width: '100%',
                    detail: { type: 'details', width: '100%', name: '' },
                    groups: [],
                    header: { type: 'stack', width: '100%', name: null },
                    footer: {
                        type: 'stack',
                        width: '100%',
                        name: null,
                        items: [
                            {
                                type: 'table',
                                width: '100%',
                                name: '',
                                rowCount: 6,
                                fixed: false,
                                minRowHeight: '24px',
                                cellStyles: {
                                    borderLeft: 'none',
                                    borderRight: 'none',
                                    borderTop: 'none',
                                    borderBottom: 'none',
                                },
                                rows: [{}, {}, {}, {}, {}, {}],
                                cells: [
                                    {
                                        r: 0,
                                        c: 0,
                                        rowspan: 3,
                                        styles: {
                                            cellAlign: 'left',
                                            verticalAlign: 'top',
                                        },
                                    },
                                    {
                                        r: 0,
                                        c: 1,
                                        styles: {
                                            verticalAlign: 'top',
                                            cellAlign: 'left',
                                        },
                                    },
                                    {
                                        r: 0,
                                        c: 2,
                                        rowspan: 3,
                                        styles: {
                                            cellAlign: 'left',
                                            verticalAlign: 'top',
                                        },
                                    },
                                    {
                                        r: 1,
                                        c: 1,
                                        styles: {
                                            verticalAlign: 'top',
                                            cellAlign: 'left',
                                        },
                                    },
                                    {
                                        r: 2,
                                        c: 1,
                                        styles: {
                                            verticalAlign: 'top',
                                            cellAlign: 'left',
                                        },
                                    },
                                    {
                                        r: 3,
                                        c: 0,
                                        rowspan: 3,
                                        styles: {
                                            cellAlign: 'left',
                                            verticalAlign: 'top',
                                        },
                                    },
                                    {
                                        r: 3,
                                        c: 1,
                                        styles: {
                                            verticalAlign: 'top',
                                            cellAlign: 'left',
                                        },
                                    },
                                    {
                                        r: 3,
                                        c: 2,
                                        rowspan: 3,
                                        styles: {
                                            cellAlign: 'left',
                                            verticalAlign: 'top',
                                        },
                                    },
                                    {
                                        r: 4,
                                        c: 1,
                                        styles: {
                                            verticalAlign: 'top',
                                            cellAlign: 'left',
                                        },
                                    },
                                    {
                                        r: 5,
                                        c: 1,
                                        styles: {
                                            verticalAlign: 'top',
                                            cellAlign: 'left',
                                        },
                                    },
                                ],
                                colCount: 3,
                                columns: [
                                    { width: '9.3%' },
                                    { width: '35.5%' },
                                    { width: '54.2%' },
                                ],
                                items: [
                                    {
                                        type: 'text',
                                        col: 0,
                                        row: 0,
                                        text: '(사업주)',
                                        styles: {
                                            textAlign: 'left',
                                            fontSize: '15px',
                                        },
                                    },
                                    {
                                        type: 'text',
                                        col: 0,
                                        row: 3,
                                        text: '(근로자)',
                                        styles: {
                                            textAlign: 'left',
                                            fontSize: '15px',
                                        },
                                    },
                                    {
                                        type: 'sign',
                                        width: 100,
                                        height: '72px',
                                        col: 2,
                                        row: 0,
                                    },
                                    {
                                        type: 'sign',
                                        width: 100,
                                        height: '72px',
                                        col: 2,
                                        row: 3,
                                    },
                                    {
                                        type: 'html',
                                        col: 1,
                                        row: 0,
                                        html: '사업체명 : ${companyName}',
                                    },
                                    {
                                        type: 'html',
                                        col: 1,
                                        row: 1,
                                        html: '주 소 : ${ownerLocation}',
                                    },
                                    {
                                        type: 'html',
                                        col: 1,
                                        row: 2,
                                        html: '대  표  자 : ${ownerName}',
                                    },
                                    {
                                        type: 'html',
                                        col: 1,
                                        row: 3,
                                        html: '주       소 : ${workerLocation}',
                                    },
                                    {
                                        type: 'html',
                                        col: 1,
                                        row: 4,
                                        html: '연 락 처 : ${workerPhone}',
                                    },
                                    {
                                        type: 'html',
                                        col: 1,
                                        row: 5,
                                        html: '성 명 : ${workerName}',
                                    },
                                ],
                            },
                        ],
                    },
                    dataRow: {
                        type: 'stack',
                        width: '100%',
                        name: null,
                        items: [
                            {
                                type: 'table',
                                width: '100%',
                                name: '',
                                rowCount: 20,
                                fixed: false,
                                minRowHeight: '24px',
                                cellStyles: {
                                    borderLeft: 'none',
                                    borderRight: 'none',
                                    borderTop: 'none',
                                    borderBottom: 'none',
                                },
                                rows: [
                                    {},
                                    {},
                                    {},
                                    {},
                                    {},
                                    {},
                                    {},
                                    {},
                                    {},
                                    {},
                                    {},
                                    {},
                                    {},
                                    {},
                                    {},
                                    {},
                                    {},
                                    {},
                                    {},
                                    { height: '46px' },
                                ],
                                cells: [
                                    {
                                        r: 6,
                                        c: 0,
                                        styles: {
                                            cellAlign: 'right',
                                            paddingBottom: '5px',
                                            paddingRight: '5px',
                                        },
                                    },
                                    {
                                        r: 9,
                                        c: 0,
                                        styles: { cellAlign: 'right' },
                                    },
                                    {
                                        r: 14,
                                        c: 0,
                                        styles: { cellAlign: 'right' },
                                    },
                                    {
                                        r: 16,
                                        c: 0,
                                        styles: { cellAlign: 'right' },
                                    },
                                    {
                                        r: 18,
                                        c: 0,
                                        styles: { cellAlign: 'right' },
                                    },
                                    {
                                        r: 19,
                                        c: 0,
                                        styles: { verticalAlign: 'middle' },
                                    },
                                ],
                                colCount: 1,
                                columns: [{ width: '100%' }],
                                items: [
                                    {
                                        type: 'text',
                                        width: '100%',
                                        col: 0,
                                        row: 2,
                                        text: '    ※ 근로계약기간을 정하는 경우에는 "    년     월     일부터     년     월     일까지" 등으로 기재',
                                        styles: { textAlign: 'left' },
                                    },
                                    {
                                        type: 'text',
                                        width: '100%',
                                        col: 0,
                                        row: 5,
                                        text: '4. 근로일 및 근로일별 근로시간',
                                        styles: {
                                            fontSize: '15px',
                                            textAlign: 'left',
                                        },
                                    },
                                    {
                                        type: 'table',
                                        width: 611.4960629921261,
                                        name: '',
                                        col: 0,
                                        row: 6,
                                        rowCount: 5,
                                        fixed: false,
                                        minRowHeight: '24px',
                                        cellStyles: {},
                                        rows: [{}, {}, {}, {}, {}],
                                        cells: [],
                                        colCount: 7,
                                        columns: [
                                            { width: '14%' },
                                            { width: '14%' },
                                            { width: '14%' },
                                            { width: '14%' },
                                            { width: '14%' },
                                            { width: '14%' },
                                            { width: '14%' },
                                        ],
                                        items: [
                                            {
                                                type: 'text',
                                                col: 0,
                                                row: 1,
                                                text: '근로시간',
                                            },
                                            {
                                                type: 'text',
                                                col: 0,
                                                row: 4,
                                                text: '휴게 시간',
                                            },
                                            {
                                                type: 'text',
                                                col: 0,
                                                row: 2,
                                                text: '시업',
                                            },
                                            {
                                                type: 'text',
                                                col: 0,
                                                row: 3,
                                                text: '종업',
                                            },
                                            {
                                                type: 'text',
                                                col: 1,
                                                row: 0,
                                                text: '월요일',
                                            },
                                            {
                                                type: 'text',
                                                col: 2,
                                                row: 0,
                                                text: '화요일',
                                            },
                                            {
                                                type: 'text',
                                                col: 3,
                                                row: 0,
                                                text: '수요일',
                                            },
                                            {
                                                type: 'text',
                                                col: 4,
                                                row: 0,
                                                text: '목요일',
                                            },
                                            {
                                                type: 'text',
                                                col: 5,
                                                row: 0,
                                                text: '금요일',
                                            },
                                            {
                                                type: 'text',
                                                col: 6,
                                                row: 0,
                                                text: '토요일',
                                            },
                                            {
                                                type: 'text',
                                                value: 'startHour',
                                                col: 1,
                                                row: 2,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'startHour',
                                                col: 2,
                                                row: 2,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'startHour',
                                                col: 3,
                                                row: 2,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'startHour',
                                                col: 4,
                                                row: 2,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'startHour',
                                                col: 5,
                                                row: 2,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'startHour',
                                                col: 6,
                                                row: 2,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'endHour',
                                                col: 1,
                                                row: 3,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'endHour',
                                                col: 2,
                                                row: 3,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'endHour',
                                                col: 3,
                                                row: 3,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'endHour',
                                                col: 4,
                                                row: 3,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'endHour',
                                                col: 5,
                                                row: 3,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'endHour',
                                                col: 6,
                                                row: 3,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'workTime',
                                                col: 1,
                                                row: 1,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'restTime',
                                                col: 1,
                                                row: 4,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'workTime',
                                                col: 2,
                                                row: 1,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'workTime',
                                                col: 3,
                                                row: 1,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'workTime',
                                                col: 4,
                                                row: 1,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'workTime',
                                                col: 5,
                                                row: 1,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'workTime',
                                                col: 6,
                                                row: 1,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'restTime',
                                                col: 2,
                                                row: 4,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'restTime',
                                                col: 3,
                                                row: 4,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'restTime',
                                                col: 4,
                                                row: 4,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'restTime',
                                                col: 5,
                                                row: 4,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'text',
                                                value: 'restTime',
                                                col: 6,
                                                row: 4,
                                                text: 'Text',
                                                styles: { fontSize: '14px' },
                                            },
                                        ],
                                    },
                                    {
                                        type: 'text',
                                        width: '100%',
                                        col: 0,
                                        row: 8,
                                        text: '5. 임  금',
                                        styles: {
                                            fontSize: '15px',
                                            textAlign: 'left',
                                        },
                                    },
                                    {
                                        type: 'text',
                                        width: '100%',
                                        col: 0,
                                        row: 10,
                                        text: '6. 연차유급휴가: 통상근로자의 근로시간에 비례하여 연차유급휴가 부여',
                                        styles: {
                                            fontSize: '15px',
                                            textAlign: 'left',
                                        },
                                    },
                                    {
                                        type: 'text',
                                        width: '100%',
                                        col: 0,
                                        row: 11,
                                        text: '7. 사회보험 적용여부(해당란에 체크)',
                                        styles: {
                                            fontSize: '15px',
                                            textAlign: 'left',
                                        },
                                    },
                                    {
                                        type: 'rbox',
                                        width: '100%',
                                        height: 25,
                                        col: 0,
                                        row: 12,
                                        itemGap: '20px',
                                        styles: { paddingLeft: '15px' },
                                        items: [
                                            {
                                                type: 'check',
                                                value: 'employmentInsurance',
                                                text: '고용보험',
                                                falseText: '고용보험',
                                                emptyText: '고용보험',
                                            },
                                            {
                                                type: 'check',
                                                value: 'industrialAccidentInsurance',
                                                text: '산재보험',
                                                falseText: '산재보험',
                                                emptyText: '산재보험',
                                            },
                                            {
                                                type: 'check',
                                                value: 'nationalPension',
                                                text: '국민연금',
                                                falseText: '국민연금',
                                                emptyText: '국민연금',
                                            },
                                            {
                                                type: 'check',
                                                value: 'healthInsurance',
                                                text: '건강보험',
                                                falseText: '건강보험',
                                                emptyText: '건강보험',
                                            },
                                        ],
                                    },
                                    {
                                        type: 'text',
                                        width: '100%',
                                        col: 0,
                                        row: 13,
                                        text: '8. 근로계약서 교부',
                                        styles: {
                                            fontSize: '15px',
                                            textAlign: 'left',
                                        },
                                    },
                                    {
                                        type: 'text',
                                        width: '640px',
                                        col: 0,
                                        row: 14,
                                        wrap: true,
                                        text: '  - "사업주"는 근로계약을 체결함과 동시에 본 계약서를 사본하여 "근로자"의 교부 요구와 관계없이 \n    "근로자"에게 고부함(근로기준법 제 17조 이행)',
                                        wordBreak: 'break-word',
                                        styles: {
                                            fontSize: '14px',
                                            lineHeight: '22px',
                                            textAlign: 'left',
                                        },
                                    },
                                    {
                                        type: 'text',
                                        width: '100%',
                                        col: 0,
                                        row: 15,
                                        text: '9. 근로계약, 취업규칙 등의 성실한 이행의무',
                                        styles: {
                                            fontSize: '15px',
                                            textAlign: 'left',
                                        },
                                    },
                                    {
                                        type: 'text',
                                        width: '640px',
                                        col: 0,
                                        row: 16,
                                        wrap: true,
                                        text: '  - 사업주와 근로자는 각자가 근로계약, 취업규칙, 단체협약을 지키고 성실하게 이행하여야 함',
                                        wordBreak: 'break-word',
                                        styles: {
                                            fontSize: '14px',
                                            lineHeight: '22px',
                                            textAlign: 'left',
                                        },
                                    },
                                    {
                                        type: 'text',
                                        width: '100%',
                                        col: 0,
                                        row: 17,
                                        text: '10. 기   타',
                                        styles: {
                                            fontSize: '15px',
                                            textAlign: 'left',
                                        },
                                    },
                                    {
                                        type: 'text',
                                        width: '640px',
                                        col: 0,
                                        row: 18,
                                        wrap: true,
                                        text: '  - 이 계약에 정함이 없는 사항은 근로기준법령에 의함',
                                        wordBreak: 'break-word',
                                        styles: {
                                            fontSize: '15px',
                                            lineHeight: '20px',
                                            textAlign: 'left',
                                        },
                                    },
                                    {
                                        type: 'html',
                                        width: '100%',
                                        col: 0,
                                        row: 0,
                                        html: '${ownerName} (이하 "사업주"라 함)과(와) ${workerName} (이하 "근로자"라 함)은 다음과 같이 근로계약을 체결한다.',
                                        styles: { fontSize: '15px' },
                                    },
                                    {
                                        type: 'html',
                                        width: '100%',
                                        col: 0,
                                        row: 1,
                                        html: '1. 근로개시일 : <span style="margin-left: 10px">${startYear} 년   ${startMonth} 월   ${startDay}일부터</span>',
                                        styles: { fontSize: '15px' },
                                    },
                                    {
                                        type: 'html',
                                        width: '100%',
                                        col: 0,
                                        row: 3,
                                        html: '2. 근 무 장 소 : <span style="margin-left: 10px">${workLocation}</span>',
                                        styles: { fontSize: '15px' },
                                    },
                                    {
                                        type: 'html',
                                        width: '100%',
                                        col: 0,
                                        row: 4,
                                        html: '3. 업무의 내용 : <span style="margin-left: 10px">${jobDescription}</span>',
                                        styles: { fontSize: '15px' },
                                    },
                                    {
                                        type: 'cbox',
                                        width: '100%',
                                        col: 0,
                                        row: 9,
                                        itemGap: '6px',
                                        styles: { paddingBottom: '5px' },
                                        items: [
                                            {
                                                type: 'html',
                                                width: '640px',
                                                right: '0px',
                                                html: '- 시간(일, 월)급 : ${salary}원(해당사항에 ○표)',
                                                styles: {
                                                    fontSize: '14px',
                                                    lineHeight: '22px',
                                                },
                                            },
                                            {
                                                type: 'html',
                                                width: '640px',
                                                right: '0px',
                                                html: '- 상여금 : 있음 (${yesBonus}) ${bonus}원, 없음 (${noBonus})',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'html',
                                                width: '640px',
                                                right: '0px',
                                                html: '- 기타급여(제수당 등) : 있음 : ${otherComensation}원(내역별 기재), 없음 (${noOther})',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'html',
                                                width: '640px',
                                                right: '0px',
                                                html: '- 초과근로에 대한 가산임금률:${probationaryWageRate} %',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'html',
                                                width: 607,
                                                right: '0px',
                                                html: '※ 단시간근로자와 사용자 사이에 근로하기로 정한 시간을 초과하여 근로하면 법정 근로',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'html',
                                                width: '590px',
                                                right: '0px',
                                                html: "시간 내라도 통상임금의 100분의 50%이상의 가산임금 지급('14.9.19 시행)",
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'html',
                                                width: '640px',
                                                right: '0px',
                                                html: '- 임금지급일 : 매월(매주 또는 매일) ${payday}일(휴일의 경우는 전일 지급)',
                                                styles: { fontSize: '14px' },
                                            },
                                            {
                                                type: 'html',
                                                width: '640px',
                                                right: '0px',
                                                html: '- 지급방법 : 근로자에게 직접지급(${directly}), 근로자 명의 예금통장에 입금(${deposit})',
                                                styles: { fontSize: '14px' },
                                            },
                                        ],
                                    },
                                    {
                                        type: 'html',
                                        width: '100%',
                                        col: 0,
                                        row: 7,
                                        html: '   ○   주휴일 : 매주   ${weekly}요일',
                                        styles: { fontSize: '15px' },
                                    },
                                    {
                                        type: 'html',
                                        value: 'signDate',
                                        width: '100%',
                                        col: 0,
                                        row: 19,
                                        html: '${value}',
                                        styles: {
                                            textAlign: 'center',
                                            fontSize: '15px',
                                        },
                                    },
                                ],
                            },
                        ],
                    },
                    styles: { fontSize: '15px' },
                },
            ],
        },
    },
    assets: { '/': [] },
    data: {
        employmentContract: {
            type: 'band',
            fields: [
                { fieldName: 'startYear', dataType: 'text', sample: '' },
                { fieldName: 'startMonth', dataType: 'text', sample: '' },
                { fieldName: 'startDay', dataType: 'text', sample: '' },
                { fieldName: 'workLocation', dataType: 'text', sample: '' },
                { fieldName: 'jobDescription', dataType: 'text', sample: '' },
                { fieldName: 'salaryType', dataType: 'text', sample: '' },
                { fieldName: 'bonus', dataType: 'number', sample: '' },
                {
                    fieldName: 'otherCompensation',
                    dataType: 'number',
                    sample: '',
                },
                { fieldName: 'salary', dataType: 'number', sample: '' },
                { fieldName: 'yesBonus', dataType: 'text', sample: '' },
                { fieldName: 'noBonus', dataType: 'text', sample: '' },
                { fieldName: 'noOther', dataType: 'text', sample: '' },
                {
                    fieldName: 'probationaryWageRate',
                    dataType: 'text',
                    sample: '',
                },
                { fieldName: 'payday', dataType: 'text', sample: '' },
                { fieldName: 'directly', dataType: 'text', sample: '' },
                { fieldName: 'deposit', dataType: 'text', sample: '' },
                { fieldName: 'weekly', dataType: 'text', sample: '' },
                { fieldName: 'signDate', dataType: 'text', sample: '' },
                { fieldName: 'ownerName', dataType: 'text', sample: '' },
                { fieldName: 'ownerLocation', dataType: 'text', sample: '' },
                { fieldName: 'companyName', dataType: 'text', sample: '' },
                { fieldName: 'workerName', dataType: 'text', sample: '' },
                { fieldName: 'workerPhone', dataType: 'text', sample: '' },
                { fieldName: 'workerLocation', dataType: 'text', sample: '' },
                {
                    fieldName: 'employmentInsurance',
                    dataType: 'bool',
                    sample: '',
                },
                {
                    fieldName: 'industrialAccidentInsurance',
                    dataType: 'bool',
                    sample: '',
                },
                { fieldName: 'nationalPension', dataType: 'bool', sample: '' },
                { fieldName: 'healthInsurance', dataType: 'bool', sample: '' },
                { fieldName: 'startHour', dataType: 'text', sample: '' },
                { fieldName: 'endHour', dataType: 'text', sample: '' },
                { fieldName: 'restTime', dataType: 'text', sample: '' },
                { fieldName: 'workTime', dataType: 'text', sample: '' },
            ],
            sample: [
                {
                    startYear: '2025',
                    startMonth: '04',
                    startDay: '01',
                    workLocation: '서울',
                    jobDescription: '음료 제조 및 손님 응대, 매장 정리 정돈',
                    salaryType: '월',
                    bonus: '1,000,000',
                    otherCompensation: '100,000',
                    salary: '2,000,000',
                    yesBonus: 'O',
                    noBonus: '',
                    noOther: '',
                    probationaryWageRate: '0',
                    payday: '25',
                    directly: 'O',
                    deposit: 'X',
                    weekly: '일',
                    signDate: '2025년    7월    15일',
                    ownerName: '김지원',
                    ownerLocation: '서울특별시 강남구 테크노밸리로 123-45',
                    companyName: '그린필드테크 주식회사',
                    workerPhone: '010-1234-5678',
                    workerLocation: '서울특별시 서대문구 메이플로 89-12',
                    workerName: '이민호',
                    employmentInsurance: 'true',
                    industrialAccidentInsurance: 'true',
                    nationalPension: 'true',
                    healthInsurance: 'true',
                    startHour: '9시',
                    endHour: '6시',
                    restTime: '1시간',
                    workTime: '8시간',
                },
            ],
        },
    },
};
