var realMapSeries = {
    report: {
        name: 'Blank Report Form',
        type: 'report',
        paperSize: 'A4',
        paperWidth: '210mm',
        paperHeight: '297mm',
        marginLeft: '12mm',
        marginRight: '12mm',
        marginTop: '15mm',
        marginBottom: '15mm',
    },
    page: {
        name: 'reportPage',
        type: 'report',
        pageHeader: { name: 'pageHeader' },
        reportHeader: { name: 'reportHeader' },
        reportFooter: { name: 'reportFooter' },
        pageFooter: {
            name: 'pageFooter',
            items: [
                {
                    type: 'rbox',
                    name: '',
                    right: 0,
                    itemGap: 4,
                    items: [
                        {
                            type: 'text',
                            value: '${page}',
                            name: '',
                            text: 'Text',
                        },
                        {
                            type: 'text',
                            name: '',
                            text: '/',
                            styles: { paddingLeft: '3px', paddingRight: '3px' },
                        },
                        {
                            type: 'text',
                            value: '${pages}',
                            name: '',
                            text: 'Text',
                        },
                    ],
                },
            ],
        },
        body: {
            itemGap: 4,
            items: [
                {
                    type: 'realmap',
                    width: '100%',
                    height: 562,
                    seriesCollection: [
                        {
                            values: [],
                            name: 'map',
                            dataUrl:
                                'https://cdn.realmap.co.kr/v1/assets/data/kr-sigun-population-density.json',
                            mapKeys: 'id',
                            pointColors:
                                "const { source } = args;\n\t\n  if (source.value > 5000) {\n    return '#395886';\n  } else if (source.value > 1000) {\n    return '#395886';\n  } else if (source.value > 500) {\n    return '#628ecb';\n  } else if (source.value > 250) {\n    return '#8aaee0';\n  } else if (source.value > 50) {\n    return '#b1c9ef';\n  }\n  return '#d5deef';",
                        },
                    ],
                    title: {
                        styles: { fontSize: '25px', fontWeight: 'bold' },
                        text: '대한민국 인구 분포 보고서 (2025년)',
                    },
                    subtitle: { visible: false, text: 'SubTitle' },
                    body: { projection: 'mercator', scroll: 0, zoom: 100 },
                    credits: { text: '', url: '' },
                    colorScale: { visible: false },
                    map: {
                        url: 'https://unpkg.com/realmap-collection@1.0.4/dist/geojson/kr-sigun-low.geo.json',
                    },
                },
                {
                    type: 'text',
                    width: '100%',
                    height: 52,
                    text: '주요 내용',
                    styles: {
                        fontSize: '18px',
                        fontWeight: 'bold',
                        textAlign: 'left',
                    },
                },
                {
                    type: 'list',
                    width: '100%',
                    ordered: false,
                    items: [
                        {
                            type: 'text',
                            text: '서울·경기·인천 수도권 지역에 인구가 집중됨',
                        },
                        {
                            type: 'text',
                            text: '부산·울산·경남 및 대구 권역에 2차 인구 밀집지 형성',
                        },
                        {
                            type: 'text',
                            text: '대전·세종·충청권을 중심으로 인구 증가세가 나타남',
                        },
                        {
                            type: 'text',
                            text: '강원도, 전라도, 경상 내륙 지역은 여전히 인구 밀도가 낮은 상태',
                        },
                    ],
                },
                { type: 'space', size: 33 },
                {
                    type: 'tableband',
                    data: 'rank',
                    width: '100%',
                    name: '',
                    detail: { type: 'details', width: '100%', name: '' },
                    colCount: 3,
                    columns: [
                        { width: '20%' },
                        { width: '20%' },
                        { width: '20%' },
                    ],
                    header: {
                        width: '100%',
                        name: '',
                        rowCount: 1,
                        fixed: false,
                        cellStyles: {},
                        rows: [{ height: '35px' }],
                        cells: [],
                        items: [
                            {
                                type: 'text',
                                width: '100%',
                                name: '',
                                col: 0,
                                row: 0,
                                text: '순위',
                            },
                            {
                                type: 'text',
                                width: '100%',
                                name: '',
                                col: 1,
                                row: 0,
                                text: '지자체',
                            },
                            {
                                type: 'text',
                                width: '100%',
                                name: '',
                                col: 2,
                                row: 0,
                                text: '인구 (백만단위)',
                            },
                        ],
                    },
                    footer: {
                        width: '100%',
                        name: '',
                        visible: false,
                        rowCount: 1,
                        fixed: false,
                        cellStyles: {},
                        rows: [{}],
                        cells: [],
                    },
                    dataRow: {
                        width: '100%',
                        name: '',
                        rowCount: 1,
                        fixed: false,
                        cellStyles: {},
                        rows: [{ height: '35px' }],
                        cells: [],
                        items: [
                            {
                                type: 'text',
                                value: 'Rank',
                                width: '100%',
                                name: '',
                                col: 0,
                                row: 0,
                            },
                            {
                                type: 'text',
                                value: 'Municipality',
                                width: '100%',
                                name: '',
                                col: 1,
                                row: 0,
                            },
                            {
                                type: 'text',
                                value: 'Population (M)',
                                width: '100%',
                                name: '',
                                col: 2,
                                row: 0,
                            },
                        ],
                    },
                },
            ],
        },
    },
    assets: { '/': [] },
    data: {
        rank: {
            type: 'band',
            fields: [
                {
                    fieldName: 'Rank',
                    label: '',
                    dataType: 'text',
                    source: '',
                    format: '',
                    sample: '',
                    description: '',
                    dateReader: null,
                },
                {
                    fieldName: 'Municipality',
                    label: '',
                    dataType: 'text',
                    source: '',
                    format: '',
                    sample: '',
                    description: '',
                    dateReader: null,
                },
                {
                    fieldName: 'Population (M)',
                    label: '',
                    dataType: 'text',
                    source: '',
                    format: '',
                    sample: '',
                    description: '',
                    dateReader: null,
                },
            ],
            sample: [
                { Rank: 1, Municipality: '서울', 'Population (M)': 9.7 },
                { Rank: 2, Municipality: '부산', 'Population (M)': 3.4 },
                { Rank: 3, Municipality: '인천', 'Population (M)': 2.9 },
                { Rank: 4, Municipality: '대구', 'Population (M)': 2.4 },
                { Rank: 5, Municipality: '대전', 'Population (M)': 1.5 },
            ],
        },
    },
};
