var dataTemplates = [
    {
        name: 'general',
        title: '일반',
        description: '일반적으로 많이 사용되는 데이터 형식들',
        items: [
            {
                name: 'tabular',
                type: 'band',
                description: 'tabular template data',
                file: 'templates/data/general/tabular.json',
            },
            {
                name: 'freeform',
                type: 'band',
                description: 'freeform template data',
                file: 'templates/data/general/freeform.json',
            },
            {
                name: 'master-detail-01',
                type: 'band',
                description: 'master/detail template master data',
                file: 'templates/data/general/master-detail-01.json',
            },
            {
                name: 'master-detail-02',
                type: 'band',
                description: 'master/detail template detail data',
                file: 'templates/data/general/master-detail-02.json',
            },
            {
                name: 'group',
                type: 'band',
                description: 'group template data',
                file: 'templates/data/general/group.json',
            },
            {
                name: 'crosstab',
                type: 'band',
                description: 'crosstab template data',
                file: 'templates/data/general/crosstab.json',
            },
            {
                name: 'mail-label',
                type: 'band',
                description: 'mail label template data',
                file: 'templates/data/general/mail-label.json',
            },
            {
                name: 'graph-chart',
                type: 'band',
                description: 'graph template chart data',
                file: 'templates/data/general/graph-chart.json',
            },
            {
                name: 'graph-table',
                type: 'band',
                description: 'graph template table data',
                file: 'templates/data/general/graph-table.json',
            },
        ],
    },
    {
        name: 'accounting',
        title: '회계',
        description: '회계 관련 데이터 형식들',
        items: [
            {
                name: 'budget-should',
                type: 'band',
                description: '예산 데이터',
                file: 'templates/data/accounting/budget-should.json',
            },
            {
                name: 'budget-result',
                type: 'band',
                description: '예산 실적 데이터',
                file: 'templates/data/accounting/budget-result.json',
            },
            {
                name: 'customer-ledger-title',
                type: 'simple',
                description: '거래처별 원장 헤더 데이터',
                file: 'templates/data/accounting/customer-ledger-title.json',
            },
            {
                name: 'customer-ledger-body',
                type: 'band',
                description: '거래처별 원장 데이터',
                file: 'templates/data/accounting/customer-ledger-body.json',
            },
            {
                name: 'inout-stats',
                type: 'band',
                description: '수입/지출 통계 데이터',
                file: 'templates/data/accounting/inout-stats.json',
            },
            {
                name: 'journal-head',
                type: 'band',
                description: '회계 분개장 head 데이터',
                file: 'templates/data/accounting/journal-head.json',
            },
            {
                name: 'journal-body',
                type: 'band',
                description: '회계 분개장 body 데이터',
                file: 'templates/data/accounting/journal-body.json',
            },
            {
                name: 'provisional-return01',
                type: 'band',
                description: '예정신고 매입/매출 현황 - 매출 데이터',
                file: 'templates/data/accounting/privisional-return-01.json',
            },
            {
                name: 'provisional-return02',
                type: 'simple',
                description: '예정신고 매입/매출 현황 - 매입 데이터',
                file: 'templates/data/accounting/privisional-return-02.json',
            },
            {
                name: 'provisional-return03',
                type: 'band',
                description: '예정신고 매입/매출 현황 - 불공제 데이터',
                file: 'templates/data/accounting/privisional-return-03.json',
            },
            {
                name: 'purchase-surtax-01',
                type: 'simple',
                description: '매입 부가세 내역 헤더 데이터',
                file: 'templates/data/accounting/purchase-surtax-01.json',
            },
            {
                name: 'purchase-surtax-02',
                type: 'band',
                description: '매입 부가세 내역 본문 데이터',
                file: 'templates/data/accounting/purchase-surtax-02.json',
            },
            {
                name: 'earned-tax-receipt',
                type: 'simple',
                description: '근로소득 원천징수 영수증 데이터',
                file: 'templates/data/accounting/earned-tax-receipt.json',
            },
            {
                name: 'retire-tax-receipt',
                type: 'simple',
                description: '퇴직소득 원천징수 영수증 데이터',
                file: 'templates/data/accounting/retire-tax-receipt.json',
            },
            {
                name: 'earned-tax-report-01',
                type: 'simple',
                description: '근로소득 원천징수부 헤더및 푸터 데이터',
                file: 'templates/data/accounting/earned-tax-report-01.json',
            },
            {
                name: 'earned-tax-report-02',
                type: 'band',
                description: '근로소득 원천징수부 월별 명세 데이터',
                file: 'templates/data/accounting/earned-tax-report-02.json',
            },
        ],
    },
    {
        name: 'hr',
        title: '인사관리',
        description: '인사관리 관련 데이터 형식들',
        items: [
            {
                name: 'personal-card-profile',
                type: 'band',
                description: '인사기록카드 프로필 데이터',
                file: 'templates/data/hr/personal-card-profile.json',
            },
            {
                name: 'personal-card-career',
                type: 'band',
                description: '인사기록카드 경력사항 데이터',
                file: 'templates/data/hr/personal-card-career.json',
            },
            {
                name: 'personal-card-family',
                type: 'band',
                description: '인사기록카드 가족관계 데이터',
                file: 'templates/data/hr/personal-card-family.json',
            },
            {
                name: 'personal-card-education',
                type: 'band',
                description: '인사기록카드 학력사항 데이터',
                file: 'templates/data/hr/personal-card-education.json',
            },
            {
                name: 'personal-card-guarantor',
                type: 'band',
                description: '인사기록카드 자격사항 데이터',
                file: 'templates/data/hr/personal-card-guarantor.json',
            },
            {
                name: 'monthly-working-report',
                type: 'band',
                description: '월간 근태관리 데이터',
                file: 'templates/data/hr/monthly-working-report.json',
            },
            {
                name: 'time-report-head',
                type: 'band',
                description: '출퇴근 관리 대장 마스터 데이터',
                file: 'templates/data/hr/time-report-head.json',
            },
            {
                name: 'time-report-list',
                type: 'band',
                description: '출퇴근 관리 대장 상세 데이터',
                file: 'templates/data/hr/time-report-list.json',
            },
            {
                name: 'resource-status',
                type: 'band',
                description: '인원 현황 보고서 데이터',
                file: 'templates/data/hr/resource-status.json',
            },
            {
                name: 'education-plan-master',
                type: 'band',
                description: '년간 교육/훈련 계획서 마스터 데이터',
                file: 'templates/data/hr/education-master.json',
            },
            {
                name: 'education-plan-detail',
                type: 'band',
                description: '년간 교육/훈련 계획서 디테일 데이터',
                file: 'templates/data/hr/education-detail.json',
            },
            {
                name: 'proof-employeement',
                type: 'band',
                description: '재직증명서',
                file: 'templates/data/hr/proof-employeement.json',
            },
            {
                name: 'employee-salary-management',
                type: 'band',
                description: '직원 급여 관리',
                file: 'templates/data/hr/employee-salary-management.json',
            },
        ],
    },
    {
        name: 'product',
        title: '생산',
        description: '생산 관련 데이터 형식들',
        items: [
            {
                name: 'daily-report-worker',
                type: 'band',
                description: '일일 생산 보고 작업자 명단',
                file: 'templates/data/product/daily-report-worker.json',
            },
            {
                name: 'daily-report-airliftStatus',
                type: 'simple',
                description: '일일 생산 보고 공수현황 데이터',
                file: 'templates/data/product/daily-report-airliftStatus.json',
            },
            {
                name: 'daily-report-production',
                type: 'band',
                description: '일일 생산 보고 생산현황 데이터',
                file: 'templates/data/product/daily-report-production.json',
            },
            {
                name: 'daily-report-faulty',
                type: 'band',
                description: '일일 생산 보고 불량현황 데이터',
                file: 'templates/data/product/daily-report-faulty.json',
            },
            {
                name: 'material-input-1',
                type: 'simple',
                description: '자재 투입 현황 마스터 데이터',
                file: 'templates/data/product/material-input1.json',
            },
            {
                name: 'material-input-2',
                type: 'band',
                description: '자재 투입 현황 작업 지시 데이터',
                file: 'templates/data/product/material-input2.json',
            },
            {
                name: 'material-input-3',
                type: 'band',
                description: '자재 투입 현황 청구/투입 데이터',
                file: 'templates/data/product/material-input3.json',
            },
            {
                name: 'monthly-claim-master',
                type: 'band',
                description: '클레임 현황 마스터 데이터',
                file: 'templates/data/product/monthly-claim-master.json',
            },
            {
                name: 'monthly-claim-detail',
                type: 'band',
                description: '클레임 현황 디테일 데이터',
                file: 'templates/data/product/monthly-claim-detail.json',
            },
            {
                name: 'monthly-report',
                type: 'band',
                description: '월별 생산실적 데이터',
                file: 'templates/data/product/monthly-report.json',
            },
            {
                name: 'product-stock1',
                type: 'band',
                description: '일일 생산/재고 기준 데이터',
                file: 'templates/data/product/product-stock1.json',
            },
            {
                name: 'product-stock2',
                type: 'band',
                description: '일일 생산/재고 계획 데이터',
                file: 'templates/data/product/product-stock2.json',
            },
            {
                name: 'product-stock3',
                type: 'band',
                description: '일일 생산/재고 재고 데이터',
                file: 'templates/data/product/product-stock3.json',
            },
            {
                name: 'quality-chart-head',
                type: 'simple',
                description: '품질관리도 헤더 데이터',
                file: 'templates/data/product/quality-chart-head.json',
            },
            {
                name: 'quality-chart-xbar',
                type: 'band',
                description: '품질 관리도 Xbar 데이터',
                file: 'templates/data/product/quality-chart-xbar.json',
            },
            {
                name: 'quality-chart-pchart',
                type: 'band',
                description: '품질 관리도 PChart 데이터',
                file: 'templates/data/product/quality-chart-pchart.json',
            },
            {
                name: 'quality-chart-statics',
                type: 'simple',
                description: '품질 관리도 Statics 데이터',
                file: 'templates/data/product/quality-chart-statics.json',
            },
            {
                name: 'annual-report-master',
                type: 'band',
                description: '연간 매입매출 보고서 마스터 데이터',
                file: 'templates/data/product/annual-report-master.json',
            },
            {
                name: 'annual-report-detail',
                type: 'band',
                description: '연간 매입매출 보고서 디테일 데이터',
                file: 'templates/data/product/annual-report-detail.json',
            },
            {
                name: 'sales-performance-master',
                type: 'band',
                description: '지점별 판매실적 마스터 데이터',
                file: 'templates/data/product/sales-performance-master.json',
            },
            {
                name: 'sales-performance-detail',
                type: 'band',
                description: '지점별 판매실적 디테일 데이터',
                file: 'templates/data/product/sales-performance-detail.json',
            },
        ],
    },
    {
        name: 'sales',
        title: '영업',
        description: '영업 관련 데이터 형식들',
        items: [
            {
                name: 'daily-report',
                type: 'band',
                description: '일일 영업활동 보고서 데이터',
                file: 'templates/data/sales/daily-report.json',
            },
            {
                name: 'daily-summary',
                type: 'simple',
                description: '일일 영업활동 보고서 summary 데이터',
                file: 'templates/data/sales/daily-summary.json',
            },
            {
                name: 'transaction-master',
                type: 'band',
                description: '거래 명세서 마스터 데이터',
                file: 'templates/data/sales/transaction-master.json',
            },
            {
                name: 'transaction-detail',
                type: 'band',
                description: '거래 명세서 디테일 데이터',
                file: 'templates/data/sales/transaction-detail.json',
            },
            {
                name: 'delivery-cert-master',
                type: 'band',
                description: '납품표 마스터 데이터',
                file: 'templates/data/sales/delivery-cert-master.json',
            },
            {
                name: 'delivery-cert-detail',
                type: 'band',
                description: '납품표 디테일 데이터',
                file: 'templates/data/sales/delivery-cert-detail.json',
            },
            {
                name: 'estimate-master',
                type: 'simple',
                description: '견적서 마스터 데이터',
                file: 'templates/data/sales/estimate-master.json',
            },
            {
                name: 'estimate-detail',
                type: 'band',
                description: '견적서 목록 데이터',
                file: 'templates/data/sales/estimate-detail.json',
            },
            {
                name: 'invoice-master',
                type: 'simple',
                description: 'Invoice 마스터 데이터',
                file: 'templates/data/sales/invoice-master.json',
            },
            {
                name: 'invoice-detail',
                type: 'band',
                description: 'Invoice 디테일 데이터',
                file: 'templates/data/sales/invoice-detail.json',
            },
            {
                name: 'order-master',
                type: 'simple',
                description: '발주서 마스터 데이터',
                file: 'templates/data/sales/order-master.json',
            },
            {
                name: 'order-detail',
                type: 'band',
                description: '발주서 디테일 데이터',
                file: 'templates/data/sales/order-detail.json',
            },
            {
                name: 'status-crosstab',
                type: 'band',
                description: '지역별 상품 영업현황표 데이터',
                file: 'templates/data/sales/status-crosstab.json',
            },
            {
                name: 'status-report',
                type: 'band',
                description: '부서별 사원별 판매현황 데이터',
                file: 'templates/data/sales/status-report.json',
            },
            {
                name: 'top-chart',
                type: 'band',
                description: 'TOP 판매액 분석 데이터',
                file: 'templates/data/sales/top-chart.json',
            },
        ],
    },
];
