name: Deploy

on:
  push:
    paths:
      - .github/workflows/deploy.yml
      - report-viewer-html/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: report-viewer-html